# Generated by Django 5.1.4 on 2025-01-08 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatars/default.svg', upload_to='avatars/'),
        ),
    ]
