# Generated by Django 5.1.4 on 2025-02-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_hashtag_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='banner',
            field=models.ImageField(default='banners/default.jpg', upload_to='banners/'),
        ),
    ]
