# Generated by Django 4.2.7 on 2025-03-29 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_profile_banner'),
        ('news', 'new_profile_fields'),
    ]

    operations = [
    ]
